import type { EpisodeSpec, StoryworldBible } from "./storyworld-types";

export const storyworlds: StoryworldBible[] = [
  {
    id: "kamau-will",
    title: "The Kamau Will",
    subtitle: "Power. Family. Truth.",
    genre: "Prestige family mystery / corporate thriller",
    format: "60–90 second vertical drama → long-form series",
    setting: "Contemporary Nairobi",
    status: "pilot-ready",
    seasonQuestion: "What does justice look like when the crime built an empire?",
    premise:
      "Industrialist Elias Kamau dies and leaves his 51% controlling stake to Amara Otieno, a 26-year-old primary-school teacher his family has never met. His first private letter to Amara says her father built the company—and Elias stole it from him.",
    visualIdentity: [
      "restrained Nairobi wealth rather than flashy luxury",
      "stone, dark timber, glass and large negative space",
      "warm ordinary spaces for Amara versus cool controlled Kamau spaces",
      "documents, signatures, empty chairs and closed doors as recurring symbols",
    ],
    soundIdentity: [
      "room tone and silence before major revelations",
      "restrained piano and low cello motif",
      "paper, pen, elevator and door sounds treated as dramatic punctuation",
    ],
    palette: ["#0b0d12", "#d6b87a", "#f2eadc", "#293746", "#6b1f2b"],
    characters: [
      {
        id: "amara",
        name: "Amara Otieno",
        age: 26,
        role: "Primary-school teacher / unexpected controlling shareholder",
        essence: "Principled, observant, grounded and difficult to intimidate.",
        appearance:
          "Kenyan woman, dark-brown skin, oval face, intelligent observant eyes, natural neat braids pulled back, slender-average build, minimal makeup.",
        wardrobe:
          "Cream blouse, muted blue cardigan, dark tailored trousers or skirt, small simple earrings; no luxury accessories in Episode 1.",
        voice:
          "Warm Kenyan English, intelligent and grounded, never theatrical; measured even when shocked.",
        visualMotifs: ["handwritten notes", "ordinary objects inside powerful spaces", "cream envelope"],
        continuityRules: [
          "Keep the same braid pattern and hairline in every shot.",
          "No sudden glamour transformation.",
          "Reactions stay restrained; confusion before awe.",
          "Cream blouse and muted blue cardigan remain unchanged throughout Episode 1.",
        ],
      },
      {
        id: "victor",
        name: "Victor Kamau Jr.",
        age: 36,
        role: "Eldest son and expected heir",
        essence: "Controlled, ambitious and convinced stewardship of the company is his duty.",
        appearance:
          "Kenyan man, dark skin, angular face, short immaculate hair, closely trimmed beard, athletic build.",
        wardrobe:
          "Perfectly tailored charcoal suit, white shirt, dark tie, restrained high-end watch.",
        voice:
          "Low, controlled Kenyan English. Anger presents as precision, not shouting.",
        visualMotifs: ["perfect symmetry", "boardroom chair", "aligned documents"],
        continuityRules: [
          "Hair, beard line and charcoal suit stay exact in Episode 1.",
          "Default posture communicates ownership of the room.",
          "Avoid exaggerated rage faces.",
        ],
      },
      {
        id: "evelyn",
        name: "Evelyn Kamau",
        age: 58,
        role: "Widow of Elias Kamau",
        essence: "Elegant, strategic and powerful through stillness.",
        appearance:
          "Elegant Kenyan woman in her late fifties, composed face, sophisticated natural styling, poised posture.",
        wardrobe:
          "Deep burgundy structured outfit, minimal but expensive jewellery.",
        voice:
          "Quiet authority; few words, precise emphasis.",
        visualMotifs: ["stillness while others react", "measured eye contact"],
        continuityRules: [
          "Never make her visibly panicked.",
          "Keep burgundy wardrobe and jewellery unchanged in Episode 1.",
          "She watches before she speaks.",
        ],
      },
      {
        id: "muriuki",
        name: "Daniel Muriuki",
        age: 64,
        role: "Family lawyer",
        essence: "Discreet, burdened and carrying knowledge accumulated over decades.",
        appearance:
          "Older Kenyan man, silver-grey short hair, weathered intelligent face, reserved expression.",
        wardrobe: "Dark conservative suit, muted tie, leather legal folder.",
        voice: "Measured older Kenyan English; professional with visible weight behind important words.",
        visualMotifs: ["legal folder", "cream paper", "pauses before disclosures"],
        continuityRules: [
          "Leather folder remains the same prop.",
          "Avoid villain framing; he is protective, not sinister.",
        ],
      },
      {
        id: "elias",
        name: "Elias Kamau",
        age: 68,
        role: "Late founder of Kamau Group",
        essence: "Visionary, complex and regretful.",
        appearance:
          "Older Kenyan man, authoritative face, greying hair and beard, dignified rather than ostentatious.",
        wardrobe: "Dark founder portrait suit; younger archival version in late-1990s engineering workwear.",
        voice: "Calm older Kenyan male voice, reflective and tired; confession delivered almost quietly.",
        visualMotifs: ["portrait", "handwriting", "archival engineering photograph"],
        continuityRules: [
          "Portrait and archival face must clearly be the same person at different ages.",
          "Voice remains calm even during confession.",
        ],
      },
    ],
  },
  {
    id: "217",
    title: "2:17",
    subtitle: "A city. A truth. A choice.",
    genre: "Climate noir / conspiracy thriller",
    format: "60–90 second vertical thriller → premium long-form",
    setting: "Nairobi, 2049",
    status: "pilot-ready",
    seasonQuestion: "Who gets protected when a city cannot protect everyone?",
    premise:
      "A municipal cartographer discovers that Nairobi's flood system is not merely predicting disasters: at exactly 2:17 a.m., it deliberately redirects water toward neighbourhoods the city's priority model considers less valuable.",
    visualIdentity: [
      "recognizable Nairobi evolved into a near-future city",
      "rain, concrete, expressways, tunnels and restrained civic technology",
      "cyan infrastructure maps; red only for sacrifice decisions",
      "avoid generic neon cyberpunk",
    ],
    soundIdentity: [
      "distant thunder and underground water movement",
      "hydraulic gates as signature sonic motif",
      "electrical hum and sudden silence before system reveals",
    ],
    palette: ["#070c12", "#59bfd4", "#d44747", "#9da8b5", "#d7d4c9"],
    characters: [
      {
        id: "amani",
        name: "Amani Njeri",
        age: 25,
        role: "Municipal mapping contractor",
        essence: "Analytical, brave and driven by spatial patterns others miss.",
        appearance:
          "Young Kenyan woman, dark skin, focused eyes, natural hair in practical protective style, lean build.",
        wardrobe: "Charcoal rain shell, muted teal underlayer, messenger bag, mapping tablet.",
        voice: "Clear Kenyan English; controlled curiosity that tightens into urgency.",
        visualMotifs: ["maps across her face", "rain on glass", "red sector overlays"],
        continuityRules: [
          "Same rain shell, bag and hair throughout pilot.",
          "No futuristic costume styling.",
        ],
      },
      {
        id: "kito",
        name: "Kito Mwangi",
        age: 29,
        role: "Hydraulic engineer",
        essence: "Practical, loyal to systems until evidence forces doubt.",
        appearance: "Young Kenyan man, dark skin, close-cropped hair, practical engineer appearance.",
        wardrobe: "Dark navy technical workwear, rolled sleeves, compact engineering tools.",
        voice: "Measured Kenyan English, technically confident until uncertainty enters.",
        visualMotifs: ["valves", "gauges", "maintenance corridors"],
        continuityRules: ["Workwear stays functional and understated.", "Avoid sci-fi armour or gadgets."],
      },
      {
        id: "mara",
        name: "Mara Wekesa",
        age: 33,
        role: "Investigative journalist",
        essence: "Curious, persistent and hungry to prove a story she once could not.",
        appearance: "Kenyan woman in her early thirties, natural textured hair, alert expressive eyes.",
        wardrobe: "Dark green structured jacket, practical trousers, phone/recorder.",
        voice: "Fast, precise Kenyan English with reporter economy.",
        visualMotifs: ["archived documents", "phone recordings", "screenshots"],
        continuityRules: ["Reporter tools are practical, not stylized.", "Maintain dark green jacket in pilot references."],
      },
      {
        id: "karanja",
        name: "Governor Daniel Karanja",
        age: 56,
        role: "Architect of Resilient Nairobi",
        essence: "Charismatic strategist who believes brutal choices can still be moral.",
        appearance: "Kenyan man in his fifties, composed, authoritative, charismatic rather than menacing.",
        wardrobe: "Minimal stone or charcoal tailoring.",
        voice: "Calm, persuasive Kenyan English; never cartoonishly evil.",
        visualMotifs: ["glass architecture", "city-wide views", "symmetry"],
        continuityRules: ["Do not code him visually as a villain.", "Keep presentation calm and civic."],
      },
    ],
  },
  {
    id: "sanctuary-7",
    title: "Sanctuary 7",
    subtitle: "Nature remembers. So do we.",
    genre: "Ecological mystery / survival adventure",
    format: "60–90 second vertical adventure → long-form → game world",
    setting: "Near-future East Africa",
    status: "pilot-ready",
    seasonQuestion: "Can something still be wild if its survival depends on human intervention?",
    premise:
      "Every animal in one of East Africa's last great wildlife refuges begins moving east at the same time. Nia Adera arrives that morning and receives a message from her scientist mother, missing for three years: if the animals are moving, they have found the door.",
    visualIdentity: [
      "beauty before danger: golden grasslands, deep forest and enormous skies",
      "natural landscapes dominate frame; technology feels intrusive",
      "predator and prey moving together is the signature impossible image",
      "underground infrastructure is concrete, corroded and monumental",
    ],
    soundIdentity: [
      "wind, insects, distant elephants and changing bird density",
      "sudden ecological silence before reveals",
      "unnatural low-frequency vibration beneath natural ambience",
    ],
    palette: ["#c69a4b", "#314b2b", "#183541", "#121414", "#dcd1b0"],
    characters: [
      {
        id: "nia",
        name: "Nia Adera",
        age: 18,
        role: "Daughter of missing ecologist Dr. Amara Adera",
        essence: "Compassionate, resilient and initially emotionally detached from conservation.",
        appearance: "Young Kenyan woman, dark skin, natural braided or twisted hair, expressive observant face.",
        wardrobe: "Urban-influenced field clothing at first: faded blue overshirt, earth-toned trousers, practical boots.",
        voice: "Young Kenyan English, direct and emotionally contained.",
        visualMotifs: ["satellite phone", "field notebook", "Koda"],
        continuityRules: ["She should initially look slightly out of place in the field.", "Clothes gradually weather over later episodes, not within pilot."],
      },
      {
        id: "jabari",
        name: "Jabari Hassan",
        age: 20,
        role: "Young ranger",
        essence: "Skilled, guarded and deeply literate in animal behaviour.",
        appearance: "Young East African man, dark skin, lean field build, observant eyes.",
        wardrobe: "Olive and sand ranger utility clothing, worn practical boots.",
        voice: "Quiet East African English; speaks only when he has something useful to say.",
        visualMotifs: ["tracks", "binoculars", "seeing movement before others"],
        continuityRules: ["Keep ranger uniform practical and non-military.", "No glossy adventure-hero styling."],
      },
      {
        id: "amara-adera",
        name: "Dr. Amara Adera",
        age: 47,
        role: "Missing ecologist",
        essence: "Brilliant, idealistic and morally compromised by what she helped build.",
        appearance: "Kenyan woman in her late forties, intelligent tired face, natural hair with subtle grey.",
        wardrobe: "Washed khaki and practical research fieldwear.",
        voice: "Calm older Kenyan female voice recorded under stress; scientific precision with maternal warmth underneath.",
        visualMotifs: ["old field tags", "recordings", "notebooks"],
        continuityRules: ["Before physical reveal, represent her through voice, photos and objects.", "Avoid glamorous scientist styling."],
      },
      {
        id: "koda",
        name: "Koda",
        age: "juvenile",
        role: "Young elephant",
        essence: "Emotional anchor and living clue to the sanctuary's hidden history.",
        appearance: "Young African elephant with a small tear in the left ear and an old tracking collar.",
        wardrobe: "None; old tracking collar only.",
        voice: "Natural elephant vocalization; distinct low contact rumble.",
        visualMotifs: ["left-ear tear", "tracking collar", "curious trunk behaviour"],
        continuityRules: ["Left-ear tear must always remain on the same ear.", "Tracking collar design never changes.", "Never anthropomorphize facial expressions."],
      },
    ],
  },
];

const kamauPilot: EpisodeSpec = {
  id: "kamau-e01",
  worldId: "kamau-will",
  number: 1,
  title: "Fifty-One Percent",
  runtimeSec: 70,
  aspectRatio: "9:16",
  episodeQuestion: "Why did Elias Kamau leave control of his empire to Amara Otieno?",
  payoff: "Amara learns that her father helped build the company.",
  cliffhanger: "Elias admits that he stole the company from Amara's father.",
  firstFrame:
    "Macro close-up of Elias Kamau's last will on a dark timber boardroom table with the line LAST WILL AND TESTAMENT visible; expensive but restrained setting, people present only as hands and silhouettes.",
  beats: [
    { id: "hook", label: "Impossible inheritance", startSec: 0, endSec: 8, purpose: "Create immediate curiosity around money, family and a stranger." },
    { id: "question", label: "Who is Amara?", startSec: 8, endSec: 22, purpose: "Contrast the dynasty with Amara's ordinary life." },
    { id: "mystery", label: "Evelyn knows", startSec: 22, endSec: 36, purpose: "Plant evidence that the family history is already compromised." },
    { id: "summons", label: "The letter", startSec: 36, endSec: 52, purpose: "Move Amara into the inheritance mystery through a physical story object." },
    { id: "payoff", label: "The other founder", startSec: 52, endSec: 64, purpose: "Answer why Amara matters." },
    { id: "reversal", label: "The theft", startSec: 64, endSec: 70, purpose: "Create a larger moral and family mystery." },
  ],
  shots: [
    { id: "k01", startSec: 0, endSec: 2, label: "The will", camera: "macro slow push-in", visual: "Cream last will and testament on a dark polished timber boardroom table, fountain pen beside it, adult hands just outside focus.", purpose: "Immediate status and mystery.", characters: [], onScreenText: ["$812 MILLION", "4 CHILDREN", "1 STRANGER"], sound: "Bare room tone, faint clock, paper movement.", promptNotes: "Cool morning light through blurred Nairobi skyline windows." },
    { id: "k02", startSec: 2, endSec: 5, label: "The patriarch", camera: "slow controlled tilt", visual: "Formal portrait of Elias Kamau in the boardroom, empty chair below it.", purpose: "Establish the dead founder as a presence.", characters: ["elias"], narration: "Elias Kamau died with four children, eighteen companies… and more than eight hundred million dollars.", sound: "Very low sub tone begins." },
    { id: "k03", startSec: 5, endSec: 8, label: "The claim", camera: "wide symmetrical boardroom", visual: "Kamau family seated along an enormous table under cool Nairobi morning light.", purpose: "Establish dynasty and stakes.", characters: ["victor", "evelyn", "muriuki"], narration: "He left control of all of it to me.", sound: "Sub tone, no melody." },
    { id: "k04", startSec: 8, endSec: 12, label: "Fifty-one percent", camera: "medium locked on lawyer", visual: "Muriuki reads from the will while Victor straightens almost imperceptibly.", purpose: "Deliver the inheritance cleanly.", characters: ["muriuki", "victor", "evelyn"], dialogue: [{ speaker: "MURIUKI", text: "I hereby transfer my fifty-one percent controlling interest in Kamau Group—to Ms Amara Otieno.", delivery: "Measured and exact." }], onScreenText: ["51% CONTROLLING INTEREST"], sound: "Paper and room tone only." },
    { id: "k05", startSec: 12, endSec: 16, label: "Who?", camera: "tight close-up", visual: "Victor looks up, disbelief contained rather than explosive.", purpose: "Turn legal information into human conflict.", characters: ["victor"], dialogue: [{ speaker: "VICTOR", text: "Who?", delivery: "Disbelief and insult in one quiet word." }], sound: "Music drops completely." },
    { id: "k06", startSec: 16, endSec: 19, label: "Amara's world", camera: "medium natural handheld-soft", visual: "Warm classroom. Amara writes 7 × 8 = ? on a board while children raise hands.", purpose: "Create immediate class and emotional contrast without depicting poverty.", characters: ["amara"], sound: "Warm classroom ambience." },
    { id: "k07", startSec: 19, endSec: 22, label: "Unknown caller", camera: "insert close-up", visual: "Amara's phone vibrates on the teacher's desk: UNKNOWN CALLER. She calmly turns it face down.", purpose: "Summon her before she knows it.", characters: ["amara"], onScreenText: ["UNKNOWN CALLER"], sound: "Phone vibration, children soft in background." },
    { id: "k08", startSec: 22, endSec: 25, label: "Accusation", camera: "medium low angle", visual: "Victor rises at the boardroom table.", purpose: "Create the obvious family theory.", characters: ["victor", "evelyn"], dialogue: [{ speaker: "VICTOR", text: "She's his daughter.", delivery: "Cold conclusion, not a question." }], sound: "Low tonal pressure returns." },
    { id: "k09", startSec: 25, endSec: 29, label: "Evelyn knows", camera: "close-up with negative space", visual: "Evelyn stays completely still as the room turns toward her.", purpose: "Plant a second mystery.", characters: ["evelyn", "victor"], dialogue: [{ speaker: "EVELYN", text: "No.", delivery: "Immediate certainty." }, { speaker: "VICTOR", text: "How do you know?", delivery: "Quietly destabilized." }], sound: "Brief low tonal hit after 'No'." },
    { id: "k10", startSec: 29, endSec: 32, label: "The summons", camera: "wide exterior", visual: "Three black executive vehicles pull quietly outside Amara's ordinary, well-kept school.", purpose: "Bring the Kamau world into Amara's world.", characters: ["muriuki"], sound: "Exterior school ambience; restrained piano enters." },
    { id: "k11", startSec: 32, endSec: 36, label: "No mistake", camera: "balanced two-shot", visual: "Amara meets Muriuki outside. She is cautious; he is formal, not threatening.", purpose: "Confirm she is the intended person.", characters: ["amara", "muriuki"], dialogue: [{ speaker: "AMARA", text: "I think you've made a mistake.", delivery: "Polite, guarded." }, { speaker: "MURIUKI", text: "No, Ms Otieno. Your name appears seventeen times in his will.", delivery: "Quiet certainty." }], sound: "Piano and natural ambience." },
    { id: "k12", startSec: 36, endSec: 40, label: "The envelope", camera: "macro handoff", visual: "Muriuki hands Amara a cream envelope with AMARA handwritten on the front.", purpose: "Introduce the recurring physical story object.", characters: ["amara", "muriuki"], onScreenText: ["AMARA"], sound: "Paper texture emphasized." },
    { id: "k13", startSec: 40, endSec: 44, label: "Why me?", camera: "over-shoulder inside vehicle", visual: "Nairobi glides softly beyond tinted glass as Amara holds the unopened envelope.", purpose: "Create intimacy before the reveal.", characters: ["amara", "muriuki"], dialogue: [{ speaker: "AMARA", text: "Why me?", delivery: "Genuine confusion." }, { speaker: "MURIUKI", text: "Mr Kamau asked me to give you this before you met his family.", delivery: "Weighted but professional." }], sound: "City muffled behind glass; restrained cello enters." },
    { id: "k14", startSec: 44, endSec: 48, label: "Open", camera: "macro close-up", visual: "Amara breaks the seal and unfolds one handwritten page.", purpose: "Slow the viewer down before the emotional turn.", characters: ["amara"], sound: "Environment rolls off toward subjective silence." },
    { id: "k15", startSec: 48, endSec: 52, label: "Elias speaks", camera: "tight close-up", visual: "Amara reads; her expression changes only slightly as Elias's voice arrives.", purpose: "Bring the dead founder into the scene.", characters: ["amara", "elias"], narration: "Amara… If you're reading this, I am dead.", sound: "Single low cello note beneath voice." },
    { id: "k16", startSec: 52, endSec: 57, label: "Two engineers", camera: "slow digital push on archival photograph", visual: "Late-1990s engineering photograph: young Elias beside another Kenyan engineer at unfinished machinery; second man partly obscured.", purpose: "Make the buried partnership tangible.", characters: ["elias"], narration: "There is something you were never told about your father.", sound: "Soft archival room tone texture." },
    { id: "k17", startSec: 57, endSec: 64, label: "The other founder", camera: "macro tracking across handwriting", visual: "Elias's handwritten letter, with the words DAVID OTIENO and BUILT THE COMPANY readable as Amara's thumb steadies the page.", purpose: "Deliver the episode answer.", characters: ["amara"], narration: "David Otieno built the company that bears my name.", onScreenText: ["DAVID OTIENO"], sound: "Music narrows to one sustained tone." },
    { id: "k18", startSec: 64, endSec: 68, label: "The confession", camera: "extreme close-up", visual: "Amara looks up from the letter, not crying, simply reorienting to a different reality.", purpose: "Deliver the reversal without melodrama.", characters: ["amara", "elias"], narration: "And I stole it from him.", sound: "Music stops before the sentence; one subtle low impact after it." },
    { id: "k19", startSec: 68, endSec: 70, label: "Title lock", camera: "static black", visual: "Black frame, elegant restrained title treatment.", purpose: "Brand the memory after the cliffhanger.", characters: [], onScreenText: ["THE KAMAU WILL", "EPISODE 1 — FIFTY-ONE PERCENT"], sound: "One breath of room tone, then cut." },
  ],
  musicDirection: "Restrained piano and cello. Legacy, control and buried guilt; never trailer percussion or generic soap-opera scoring.",
  subtitleDirection: "Premium clean sans-serif, maximum two lines, lower-middle safe zone. No bouncing word-by-word captions; occasional emphasis only on story-critical words.",
  platformCaption: "A billionaire dies. His four children expect to inherit his empire. Instead, he leaves control of everything to a 26-year-old teacher they have never met. The Kamau Will — Episode 1: Fifty-One Percent.",
  pinnedComment: "If someone left you control of an $812M company—and then admitted it was built on something stolen from your family—would you take it?",
};

const twoSeventeenPilot: EpisodeSpec = {
  id: "217-e01",
  worldId: "217",
  number: 1,
  title: "The Map",
  runtimeSec: 70,
  aspectRatio: "9:16",
  episodeQuestion: "How can the city know exactly when Amani's neighbourhood will flood?",
  payoff: "Amani proves the historical red zones align with controlled relief gates.",
  cliffhanger: "The map is not predicting floods. It is scheduling them.",
  firstFrame: "Rain-soaked wristwatch reading 2:17 against a dark Nairobi street while water rises around a curb drain.",
  beats: [
    { id: "hook", label: "Tomorrow at 2:17", startSec: 0, endSec: 8, purpose: "State an impossible prediction." },
    { id: "map", label: "To the minute", startSec: 8, endSec: 24, purpose: "Show the anomaly is too precise to be weather forecasting." },
    { id: "history", label: "Pattern", startSec: 24, endSec: 46, purpose: "Turn one anomaly into a repeated system pattern." },
    { id: "home", label: "Her street", startSec: 46, endSec: 60, purpose: "Make the system personal." },
    { id: "reversal", label: "Scheduling", startSec: 60, endSec: 70, purpose: "Reveal human agency behind the flood." },
  ],
  shots: [
    { id: "t01", startSec: 0, endSec: 4, label: "2:17", camera: "macro street-level close-up", visual: "Rain beads on a dark wristwatch reading 2:17; curb water moves in an unexpected direction.", purpose: "Immediate mystery image.", characters: [], narration: "At 2:17 tomorrow morning, my neighbourhood will flood.", sound: "Rain, low water movement, distant thunder." },
    { id: "t02", startSec: 4, endSec: 8, label: "Red sector", camera: "over-shoulder map screen", visual: "Amani studies a civic map of Nairobi. One district pulses red with RELIEF SECTOR 12 and 02:17.", purpose: "Attach the impossible time to a system.", characters: ["amani"], onScreenText: ["RELIEF SECTOR 12", "02:17", "EXPECTED DEPTH 1.8 M"], sound: "Electrical room hum." },
    { id: "t03", startSec: 8, endSec: 15, label: "Moderate rain", camera: "screen insert then profile", visual: "Weather forecast shows moderate rain, while Amani compares it to the severe flood depth forecast.", purpose: "Show contradiction.", characters: ["amani"], dialogue: [{ speaker: "AMANI", text: "That doesn't make sense.", delivery: "Quiet analytical disbelief." }], sound: "Rain against window." },
    { id: "t04", startSec: 15, endSec: 24, label: "Kito", camera: "split visual / call close-ups", visual: "Amani calls Kito; he is in a hydraulic maintenance space.", purpose: "Let a trusted engineer offer the normal explanation, then undermine it.", characters: ["amani", "kito"], dialogue: [{ speaker: "KITO", text: "It's a predictive layer. It shows where flooding might happen.", delivery: "Routine technical confidence." }, { speaker: "AMANI", text: "Tomorrow?", delivery: "Testing him." }, { speaker: "KITO", text: "Yes.", delivery: "Matter-of-fact." }, { speaker: "AMANI", text: "To the minute?", delivery: "Quiet." }], sound: "Call compression, machinery underneath Kito." },
    { id: "t05", startSec: 24, endSec: 34, label: "Archive", camera: "rapid controlled map montage", visual: "Amani pulls historical flood maps: April 2047, November 2047, March 2048. Each red sector matches an actual flood record.", purpose: "Establish repeated pattern, not coincidence.", characters: ["amani"], onScreenText: ["APR 2047", "NOV 2047", "MAR 2048"], sound: "Subtle rhythmic data ticks, no beat." },
    { id: "t06", startSec: 34, endSec: 46, label: "Infrastructure overlay", camera: "top-down digital map animation", visual: "She overlays stormwater infrastructure. Every flooded district sits downstream of a controlled relief gate.", purpose: "Connect outcome to controllable infrastructure.", characters: ["amani"], sound: "Hydraulic motif begins quietly." },
    { id: "t07", startSec: 46, endSec: 55, label: "Her building", camera: "screen to face rack focus", visual: "Amani zooms into tomorrow's red zone until her own street and building number appear.", purpose: "Make abstract system personally dangerous.", characters: ["amani"], sound: "Rain louder, room tone falls away." },
    { id: "t08", startSec: 55, endSec: 60, label: "The question", camera: "tight profile", visual: "Red map light crosses Amani's face.", purpose: "Set up the final inference.", characters: ["amani", "kito"], dialogue: [{ speaker: "AMANI", text: "Kito…", delivery: "Recognition, not panic." }, { speaker: "KITO", text: "What?", delivery: "Now concerned." }], sound: "Hydraulic metal strain begins." },
    { id: "t09", startSec: 60, endSec: 67, label: "The gate", camera: "underground cinematic reveal", visual: "Somewhere beneath Nairobi, a huge relief gate begins to open. Water changes direction.", purpose: "Reveal physical agency before verbal conclusion.", characters: [], sound: "Deep hydraulic release and rushing water." },
    { id: "t10", startSec: 67, endSec: 70, label: "Scheduling", camera: "black title lock", visual: "Black after a final flash of the red map.", purpose: "State the franchise thesis as cliffhanger.", characters: ["amani"], narration: "The map isn't predicting the floods. It's scheduling them.", onScreenText: ["2:17", "EPISODE 1 — THE MAP"], sound: "Hard cut after the word 'them'." },
  ],
  musicDirection: "Sparse low synth texture beneath real rain and hydraulic machinery. The infrastructure itself is the score.",
  subtitleDirection: "Compact white captions with occasional cyan system terms and red only for sacrifice-zone data.",
  platformCaption: "Amani discovers tomorrow's flood map. The strange part is not where the water will go. It is that the city knows the exact minute.",
  pinnedComment: "If a flood-control system could save most of a city only by sacrificing one neighbourhood, who should be allowed to make that decision?",
};

const sanctuaryPilot: EpisodeSpec = {
  id: "sanctuary-e01",
  worldId: "sanctuary-7",
  number: 1,
  title: "The Migration",
  runtimeSec: 70,
  aspectRatio: "9:16",
  episodeQuestion: "Why are predator and prey moving together in the same direction?",
  payoff: "The migration was predicted by Nia's missing mother three years earlier.",
  cliffhanger: "Her mother's message says the animals are moving because 'they've found the door.'",
  firstFrame: "A lion and zebra moving in the same direction through golden grass, neither reacting to the other.",
  beats: [
    { id: "hook", label: "Everything is running", startSec: 0, endSec: 14, purpose: "Show impossible animal behaviour before explanation." },
    { id: "arrival", label: "Nia", startSec: 14, endSec: 28, purpose: "Bring the protagonist into the anomaly." },
    { id: "koda", label: "The tag", startSec: 28, endSec: 44, purpose: "Connect the migration to Nia's missing mother." },
    { id: "phone", label: "Impossible call", startSec: 44, endSec: 58, purpose: "Turn personal mystery into direct contact." },
    { id: "door", label: "The warning", startSec: 58, endSec: 70, purpose: "Introduce the hidden infrastructure mystery." },
  ],
  shots: [
    { id: "s01", startSec: 0, endSec: 5, label: "Together", camera: "long-lens low wide", visual: "Lion and zebra move through golden grass in the same direction, only metres apart, neither hunting nor fleeing the other.", purpose: "Create an impossible ecological image.", characters: [], narration: "At 6:42 this morning, every animal in Sanctuary 7 started running.", sound: "Wind, hooves, distant low elephant calls." },
    { id: "s02", startSec: 5, endSec: 10, label: "Scale", camera: "aerial reveal", visual: "Elephants, buffalo, antelope and birds all stream east through a vast East African landscape.", purpose: "Show this is system-scale behaviour.", characters: [], sound: "Natural migration sound; no music yet." },
    { id: "s03", startSec: 10, endSec: 14, label: "What they weren't doing", camera: "compressed telephoto", visual: "Predator and prey cross the same frame without conflict.", purpose: "Specify what makes the migration impossible.", characters: [], narration: "The strange part wasn't that they were running. It was what they weren't doing.", sound: "Bird ambience abruptly thins." },
    { id: "s04", startSec: 14, endSec: 21, label: "Arrival", camera: "vehicle interior to exterior", visual: "Nia arrives in a ranger vehicle, staring at the migration while Jabari watches the horizon.", purpose: "Anchor viewer in protagonists.", characters: ["nia", "jabari"], dialogue: [{ speaker: "NIA", text: "Is this normal?", delivery: "Trying to sound casual." }, { speaker: "JABARI", text: "No.", delivery: "Immediate." }], sound: "Vehicle engine shuts off; field ambience dominates." },
    { id: "s05", startSec: 21, endSec: 28, label: "Nothing normal", camera: "medium on Jabari then sky whip", visual: "A flock erupts from the forest behind Jabari as he keeps watching the ground movement.", purpose: "Increase environmental unease.", characters: ["nia", "jabari"], dialogue: [{ speaker: "JABARI", text: "Nothing about this is normal.", delivery: "Quiet fact." }], sound: "Wing burst and sudden insect silence." },
    { id: "s06", startSec: 28, endSec: 36, label: "Koda", camera: "ground-level intimate close-up", visual: "An injured young elephant stands beside the track. Nia carefully approaches; old tracking collar visible, left ear torn.", purpose: "Introduce emotional anchor and continuity character.", characters: ["nia", "koda"], sound: "Koda contact rumble, wind softens." },
    { id: "s07", startSec: 36, endSec: 44, label: "The tag", camera: "macro insert to Nia reaction", visual: "Tracking tag stamped A. ADERA — S7. Nia recognizes the name.", purpose: "Connect mystery to family history.", characters: ["nia", "koda"], onScreenText: ["A. ADERA — S7"], dialogue: [{ speaker: "JABARI", text: "You know that name?", delivery: "Careful." }, { speaker: "NIA", text: "My mother.", delivery: "Almost to herself." }], sound: "Single low tonal bed begins." },
    { id: "s08", startSec: 44, endSec: 52, label: "The phone", camera: "bag insert then tight close-up", visual: "An old satellite phone begins ringing in Nia's bag. Display: DR. AMARA ADERA.", purpose: "Create impossible contact from the missing mother.", characters: ["nia", "amara-adera"], onScreenText: ["INCOMING: DR. AMARA ADERA"], dialogue: [{ speaker: "NIA", text: "That's impossible.", delivery: "Barely audible." }], sound: "Harsh satellite ringtone against natural field ambience." },
    { id: "s09", startSec: 52, endSec: 62, label: "The warning", camera: "tight on Nia, no cutaway", visual: "Nia answers. Static; she listens as the landscape seems to hold still behind her.", purpose: "Deliver the first message from Amara.", characters: ["nia", "amara-adera"], dialogue: [{ speaker: "AMARA ADERA", text: "Nia… If the animals are moving…", delivery: "Recorded, degraded, urgent but controlled." }], sound: "Satellite static; natural ambience drops almost entirely." },
    { id: "s10", startSec: 62, endSec: 70, label: "The door", camera: "mountain wide to darkness", visual: "Koda turns toward a distant mountain. Deep underground, unseen machinery unlocks behind rock and concrete.", purpose: "Open the hidden-infrastructure mystery.", characters: ["koda", "amara-adera"], dialogue: [{ speaker: "AMARA ADERA", text: "…they've found the door.", delivery: "Final warning through static." }], onScreenText: ["SANCTUARY 7", "EPISODE 1 — THE MIGRATION"], sound: "Subterranean mechanical lock disengages beneath a deep animal rumble." },
  ],
  musicDirection: "Begin with almost no score. Let wildlife and silence carry tension; introduce an almost sub-audible low frequency only after the tracking tag appears.",
  subtitleDirection: "Clean premium captions; use no playful animal styling. Dialogue remains secondary to images and natural sound.",
  platformCaption: "At 6:42, predator and prey started moving in the same direction. Then Nia's missing mother's phone called.",
  pinnedComment: "What could make predators stop hunting and move with their prey?",
};

export const pilotEpisodes: EpisodeSpec[] = [kamauPilot, twoSeventeenPilot, sanctuaryPilot];

export function getStoryworld(id: string) {
  return storyworlds.find((world) => world.id === id);
}

export function getPilotEpisode(worldId: string) {
  return pilotEpisodes.find((episode) => episode.worldId === worldId);
}
