import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

import {
  buildNarrationText,
  estimateNarration,
  timingsFromAlignment,
} from "@/lib/narration";
import type { EpisodeProject, NarrationTrack } from "@/lib/types";

const BodySchema = z.object({
  project: z.any(),
  provider: z.enum(["estimate", "elevenlabs"]),
  wordsPerMinute: z.number().min(80).max(240).optional(),
  voiceId: z.string().optional(),
  modelId: z.string().optional(),
});

export async function POST(request: NextRequest) {
  try {
    const body = BodySchema.parse(await request.json());
    const project = body.project as EpisodeProject;

    if (!project?.scenes?.length) {
      return NextResponse.json(
        { error: "The episode has no scenes to narrate." },
        { status: 400 }
      );
    }

    if (body.provider === "estimate") {
      return NextResponse.json({
        track: estimateNarration(project, body.wordsPerMinute || 155),
        audioGenerated: false,
      });
    }

    const apiKey = process.env.ELEVENLABS_API_KEY;
    const voiceId =
      body.voiceId?.trim() || process.env.ELEVENLABS_VOICE_ID;
    const modelId =
      body.modelId?.trim() ||
      process.env.ELEVENLABS_MODEL_ID ||
      "eleven_multilingual_v2";

    if (!apiKey) {
      return NextResponse.json(
        {
          error:
            "ELEVENLABS_API_KEY is not configured in .env.local.",
        },
        { status: 503 }
      );
    }

    if (!voiceId) {
      return NextResponse.json(
        {
          error:
            "Enter a voice ID or set ELEVENLABS_VOICE_ID in .env.local.",
        },
        { status: 400 }
      );
    }

    const built = buildNarrationText(project);

    if (!built.text.trim()) {
      return NextResponse.json(
        { error: "The episode narration is empty." },
        { status: 400 }
      );
    }

    const response = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(
        voiceId
      )}/with-timestamps?output_format=mp3_44100_128`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "xi-api-key": apiKey,
        },
        body: JSON.stringify({
          text: built.text,
          model_id: modelId,
          voice_settings: {
            stability: 0.48,
            similarity_boost: 0.82,
            speed: 1,
          },
        }),
      }
    );

    const data = await response.json();

    if (!response.ok) {
      return NextResponse.json(
        {
          error:
            data?.detail?.message ||
            data?.detail ||
            data?.message ||
            "ElevenLabs narration request failed.",
        },
        { status: response.status }
      );
    }

    // Original-text alignment preserves the character offsets generated by
    // buildNarrationText(). normalized_alignment may alter offsets.
    const alignment = data.alignment;

    if (
      !alignment?.characters ||
      !alignment?.character_start_times_seconds ||
      !alignment?.character_end_times_seconds
    ) {
      return NextResponse.json(
        {
          error:
            "The narration provider returned audio without usable character timing.",
        },
        { status: 502 }
      );
    }

    const sentences = timingsFromAlignment(project, alignment);
    const durationSec =
      alignment.character_end_times_seconds[
        alignment.character_end_times_seconds.length - 1
      ] || 0;

    const track: NarrationTrack = {
      provider: "elevenlabs",
      voiceId,
      modelId,
      audioDataUrl: `data:audio/mpeg;base64,${data.audio_base64}`,
      mimeType: "audio/mpeg",
      durationSec,
      generatedAt: new Date().toISOString(),
      sentences,
      captionStyle: "kinetic",
    };

    return NextResponse.json({
      track,
      audioGenerated: true,
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        error: error?.message || "Unable to generate narration.",
      },
      { status: 500 }
    );
  }
}
